### ISSUE TITLE
Alt-c is accessible on OS X with iTerm2 as Esc-c

### ISSUE THREAD

**Issue by tchajed** [fisherman/fzf#11]
On OS X, alt is used to input special characters, so Alt-c isn't observed by fish. I am able to access the keybinding as Esc-c, however.

I don't trust my understanding of terminal emulation enough to document this except for the special case of OS X and iTerm2.

I'm using OS X 10.10.5 with iTerm2 3.0.10 and fish 2.3.1.

**Comment by jethrokuan** [comment]
Thanks for letting me know, I run a linux machine so I'm unaware of the OSX subtleties. The keybindings are based off fzf project, and are unlikely to change. It's easy to modify the keybindings though: maintaining a OSX friendly branch wouldn't be too hard. 

I rarely use alt-c, because `z` is way faster for directory-changing (at least for me).

**Comment by tchajed** [comment]
Just to clarify - the bindings as provided all work. What I was proposing was just a comment in the README that on OS X you can press esc-c to change directories, although I don't know if this will work for everyone.

**Comment by tchajed** [comment]
There is one cool thing alt-c lets you do: if you've typed out a comment but realize you're in the wrong directory, you can change it without disrupting what you've typed. Doesn't happen that often, but I have wanted such a feature before.

Other than that I do tend to use `z`.

**Comment by jethrokuan** [comment]
A quick search tells me using Esc as the alt key is specific to iterm. I'm not sure this would within the scope of the repo. Perhaps a general hint to clue people in on modifier key emulation in different terminals would be good. I'm open to PRs. In any case, I'm sure this issue would be beneficial to people who encounter the same issue as you.

Thanks for sharing that cool tip! Didn't know it worked that way :smile:
