### ISSUE TITLE
Take command into account?

### ISSUE THREAD

**Issue by nabsiddiqui** [fisherman/fzf#13]
In ZSH with FZF, if you type in something like cd and hit CTRL R it will show you past commands with cd only. With the fisher plugin, it shows all the older commands.  Is there a reason for the difference?

**Comment by jethrokuan** [comment]
This was just how the original fish plugin for fzf was written, but the behaviour you mentioned makes sense. Fixed it with the latest commit, so `fisher update fzf` should fix things.
