### ISSUE TITLE
Add FZF_*_OPTS support

### ISSUE THREAD

**Issue by neersighted** [fisherman/fzf#14]
Supporting the new option variables added in this fzf commit would be great! Thanks!

https://github.com/junegunn/fzf/commit/c39c039e155c50bcf8fecc5956c4bdd3b5c6bea1

**Comment by jethrokuan** [comment]
I think that should do it.

I tried `set -U FZF_CTRL_T_OPTS "--reverse"` and it seemed to work, but I'm not to familiar with what options I can pass in (it's not really documented as well) so let me know if I missed anything out.

**Comment by neersighted** [comment]
Working great for me... Thanks!
