### ISSUE TITLE
Multiline history 

### ISSUE THREAD

**Issue by leiserfg** [fisherman/fzf#15]
Try to find a `for` in the history and you will get just the first line. For avoid it, I replace history command with:
```fish
function _history
    if test -e ~/.local/share/fish/fish_history
        cat ~/.local/share/fish/fish_history | grep "^\- cmd: " | sed 's/\- cmd: //'
    else if test -e ~/.config/fish/fish_history
        cat ~/.config/fish/fish_history | grep "^\- cmd: " | sed 's/\- cmd: //'
    else
        history
    end
end
```

**Comment by jethrokuan** [comment]
I'm not sure if I should "fix" this particular behaviour. I'm using `history` how fish intended it to be used. Perhaps people actually want individual lines of code, rather than the whole block.

Nevertheless, I could add this as an option. Would love to hear your opinion.

**Comment by leiserfg** [comment]
In fish, history does manage multiline commands. If you have doubts, write for and press `up` up to find one and you will se it multiline. The matter is that when you call history it use the same separator, but even the inner $history  var the multiline commands are stored as one.

**Comment by jethrokuan** [comment]
you're right, wonder where I got that impression from. Anyway, I pushed a fix, hopefully it works like you want it to.

**Comment by jethrokuan** [comment]
Should be fully fixed with the latest commit.
