### ISSUE TITLE
Keybindings not compatible with new keybindings in fish 2.4.0

### ISSUE THREAD

**Issue by yegorius** [fisherman/fzf#22]
Fish 2.4.0 introduces new default keybindings for interaction with system clipboard.
`Ctrl-x` is now used for copying kill-buffer to system clipboard.
`Alt-c` is also occupied by "Capitalize current word" action.
What about new default keybindings for `fzf`?

**Comment by jethrokuan** [comment]
Thanks for letting me know. Do you have any good suggestions? I do not wish to deviate too far from the original `fzf` keybindings.

**Comment by yegorius** [comment]
Yep, I have just changed my `fzf` keybindings like this and it feels quite comfortable:
- `Ctrl-t`: file finder -> `Ctrl-f`
`Ctrl-t` is now "Transpose last two characters" and `Ctrl-f` is easy to remember because `f` is like **F**ile
- `Ctrl-r`: no conflict and is very nice since this replicates bash history search feature
- `Ctrl-x`: execute past cmd -> `Alt-x`
- `Alt-c`: cd into directories -> `Alt-d` (`d` like **d**irectory)
What do you think?

**Comment by jethrokuan** [comment]
`Ctrl-f` sounds interesting, but might it have conflicts with terminal emulators, I'm sure some support text search within terminals. I like `Alt-d` and `Alt-x`.

Changing this would affect the many users out there who update the plugin, and it would likely come as a surprise to most of them. I'll figure out a way to phase it in.

**Comment by yegorius** [comment]
I have used Gnome Terminal, Konsole and a multitude of Linux terminal emulators, and AFAIK most of them use prefixed keybindings like `Shift-Ctrl-f` or emacs/vi keybindings.

**Comment by jethrokuan** [comment]
@yegorius sorry this took so long. I pushed up an update to the plugin. The README reflects the new keybindings, as well as gives instructions as to how to use them instead. I'm keeping the legacy keybindings for now, so I don't break other people's systems.

https://github.com/fisherman/fzf/commit/12af3d11a6d09885ae21dd7726e8de9c66df6865
