### ISSUE TITLE
prompt error message when open new terminal

### ISSUE THREAD

**Issue by TangMonk** [fisherman/fzf#23]
error message as following

```
Last login: Tue Dec 20 16:28:26 on ttys010
You have new mail.
set: Warning: $PATH entry "/Users/tangmonk/.fzf/bin" is not valid (No such file or directory)
set: Warning: $PATH entry "/Users/tangmonk/activator-dist-1.3.10/bin" is not valid (No such file or directory)
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

**Comment by jethrokuan** [comment]
could you run `__fzf_install`?

**Comment by TangMonk** [comment]
@jethrokuan fzf warning disappeared, but another warning still:

```/Users/tangmonk/activator-dist-1.3.10/bin ```

**Comment by jethrokuan** [comment]
@TangMonk this plugin doesn't mess with `$PATH` in a way that would cause this `activator-dist` issue. You should check if the path indeed exists, and if not, which plugin/utility installs it.

**Comment by TangMonk** [comment]
@jethrokuan , thanks
