### ISSUE TITLE
Only worked once in original shell

### ISSUE THREAD

**Issue by tanc** [fisherman/fzf#24]
I can't seem to get this working when I open a new shell in iTerm2 (or terminal.app) on OS X. The fzf command is installed and works independently when typing `fzf`, its just the keybindings that don't work. For example, in my open shell where I first installed this plugin I can use ctrl + r to open the fzf command search but when I open a new window then ctrl + r does nothing. Any ideas?

**Comment by jethrokuan** [comment]
@tanc apologies for the late reply. Did you install the plugin through Fisherman?

**Comment by tanc** [comment]
No problem @jethrokuan! I did indeed install through Fisherman

**Comment by jethrokuan** [comment]
@tanc what fisherman does is to copy the keybinding settings from this plugin into a fish-specific file. Could I see the results of `cat ~/.config/fish/functions/fish_user_key_bindings.fish`? Also, note that in the newer fish versions, the Ctrl key combinations have their own utilities (Ctrl-t is transpose characters, for example), so you might want to consider the legacy keybinding flag, as described in the README.

**Comment by tanc** [comment]
```
$ cat ~/.config/fish/functions/fish_user_key_bindings.fish
function fish_user_key_bindings
    ### bang-bang ###
    bind ! __history_previous_command
    bind '$' __history_previous_command_arguments
    ### bang-bang ###
    ### fzf ###
    set -q FZF_LEGACY_KEYBINDINGS
    or set -l FZF_LEGACY_KEYBINDINGS 1
    if test "$FZF_LEGACY_KEYBINDINGS" -eq 1
        bind \ct '__fzf_find_file'
        bind \cr '__fzf_reverse_isearch'
        bind \cx '__fzf_find_and_execute'
        bind \ec '__fzf_cd'
        bind \eC '__fzf_cd_with_hidden'
        if bind -M insert >/dev/null ^/dev/null
            bind -M insert \ct '__fzf_find_file'
            bind -M insert \cr '__fzf_reverse_isearch'
            bind -M insert \cx '__fzf_find_and_execute'
            bind -M insert \ec '__fzf_cd'
            bind -M insert \eC '__fzf_cd_with_hidden'
        end
    else
        bind \cf '__fzf_find_file'
        bind \cr '__fzf_reverse_isearch'
        bind \ex '__fzf_find_and_execute'
        bind \ed '__fzf_cd'
        bind \eD '__fzf_cd_with_hidden'
        if bind -M insert >/dev/null ^/dev/null
            bind -M insert \cf '__fzf_find_file'
            bind -M insert \cr '__fzf_reverse_isearch'
            bind -M insert \ex '__fzf_find_and_execute'
            bind -M insert \ed '__fzf_cd'
            bind -M insert \eD '__fzf_cd_with_hidden'
        end
    end
    ### fzf ###
end
```

**Comment by jethrokuan** [comment]
hmm it does look like everything is in order. Could you run `fish_user_key_bindings` and see if the keybindings work?

**Comment by tanc** [comment]
Opening a new shell and running `fish_user_key_bindings` does not make the keybindings work for some reason.

**Comment by jethrokuan** [comment]
@tanc one thing that came to mind is that you may have overwritten `fish_user_key_bindings` somewhere else, perhaps manually in a `config.fish` file. This happened in this issue: https://github.com/fisherman/fzf/issues/10

What's the result of `functions fish_user_key_bindings`?

**Comment by tanc** [comment]
Ah, brilliant! That's exactly the problem:

```
function fish_user_key_bindings
	bind \e\e 'thefuck-command-line'  # Bind EscEsc to thefuck
end
```

I've removed that and its working as expected. Thanks so much for your help!

**Comment by jethrokuan** [comment]
no problem (:
