### ISSUE TITLE
Space added after ctrl + f selection made

### ISSUE THREAD

**Issue by tanc** [fisherman/fzf#25]
When choosing a file using ctrl + f the file path is returned inside double quotes but with a space before the closing double quote. For example:

`vi "sites/default/settings.local.php "`

**Comment by jethrokuan** [comment]
Can reproduce, looks like there's no need to escape the file names anymore, given they're in quotes. Pushed a fix to master, run `fisher u fzf` to pull down the changes 😄

**Comment by tanc** [comment]
Perfect! Thanks
