### ISSUE TITLE
Incorrect history

### ISSUE THREAD

**Issue by giodamelio** [fisherman/fzf#29]
When I use the reverse history search it is not giving me my up to date history. It all comes down to the [`functions/__fish_history.fish`](https://github.com/fisherman/fzf/blob/master/functions/__fish_history.fish) script. Manually printing the history files with `tac` or `tail -r` gives me old history. The `history` command works fine though.

Is there a reason that it is being tried manually first? It seems like more work and a duplication of logic that fishes build in `history` command should take care of.

**Comment by jethrokuan** [comment]
The reason __fish_history exists is because `history` doesn't support multi-line commands. If you're not getting up-to-date history, then it is likely that __fish_history is looking at another history file. This all depends on how you installed and configured fish.

**Comment by giodamelio** [comment]
Oh, It turns out I had an old history file left over from when fish used to put it in `~/.config/fish`. Removing that makes it work all fine. Thanks.
