### ISSUE TITLE
Change FZF_DEFAULT_COMMAND with new key bindings

### ISSUE THREAD

**Issue by magnus-staberg** [fisherman/fzf#31]
I modify the default command by
```
set -gx FZF_DEFAULT_COMMAND 'ag -l --hidden --ignore .git'
set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
```
which doesn't work together with
`set -U FZF_LEGACY_KEYBINDINGS 0`
because search binding is F instead of T (I guess).

I tried changing variable name to `FZF_CTRL_F_COMMAND` but doesn't work.

Would be great if we could modify `FZF_DEFAULT_COMMAND` with the new key bindings.

**Comment by jethrokuan** [comment]
@magnus-staberg the options for this plugin are different from the options listed in the original README for `fzf`.

try this instead:
```
set -gx FZF_DEFAULT_COMMAND 'ag -l --hidden --ignore .git'
set -gx FZF_CD_COMMAND "$FZF_DEFAULT_COMMAND"
```
Realized I documented the ability to change options, but not the ability to change the command.

**Comment by magnus-staberg** [comment]
Great, it works, thank you!
