### ISSUE TITLE
Multiple match selection

### ISSUE THREAD

**Issue by EfforiaKnight** [fisherman/fzf#32]
When I trying to select multiple matched from 

> __fzf_find_file

It selects only the first selection
![image](https://cloud.githubusercontent.com/assets/18498403/23331300/c443b516-fb6b-11e6-853d-423375638082.png)
![image](https://cloud.githubusercontent.com/assets/18498403/23331315/094231e2-fb6c-11e6-8a0d-6c26923614a3.png)

**Comment by jethrokuan** [comment]
Yup the plugin doesn't support multi-selects right now, but this should be trivial.

**Comment by EfforiaKnight** [comment]
Thanks. 
Looking forward for the fix.

**Comment by jethrokuan** [comment]
Should be fixed with https://github.com/fisherman/fzf/commit/bf0af7188e2fcbaf47230a704252394d93b6eeaa. Let me know if it works.

**Comment by EfforiaKnight** [comment]
Works! Thanks!
BTW can you please explain why you added this block of code?
`  if not test "$dir" = "."`
    `commandline -t ""`
`  end`

**Comment by jethrokuan** [comment]
@EfforiaKnight this was from the original fish wrapper from their repo. I'm a little rusty from fish shell scripting... and thought that dir was something fish automatically set, like `$PWD`. Wasn't reading too closely.

On that note I was wondering if it'd be more useful if absolute paths were returned instead of relative ones. That could really lengthen the return results though.

**Comment by EfforiaKnight** [comment]
Thanks! 
I don't think that absolute path will be more useful. We search file from current directory so why would we need the whole path? 
We can do like ls -l and then search for files, it will print out absolute path for each.

**Comment by jethrokuan** [comment]
because this gets appended to fish history, and you might want to rerun
that command and have it be valid regardless of which folder you're in.

Regards,
Jethro Kuan

**Comment by EfforiaKnight** [comment]
I see... Didn't thought using it like this. 
This can be helpful. 
Maybe add an option to default search OPTS?

**Comment by jethrokuan** [comment]
Good idea. I'll do that soon.
