### ISSUE TITLE
`__fzf_reverse_isearch` cannot replace commandline well with a history containing `%`

### ISSUE THREAD

**Issue by yuttie** [fisherman/fzf#33]
Hi, I'm new to fish shell, and I'm happy to find such a nice plugin are already there 😄.
Thanks for your work.

I have commandline histories containing `%` in their arguments, like `cp file /some/dir/file-(date +%Y%m%d)`.  Because the [current implementation](https://github.com/fisherman/fzf/blob/12af3d11a6d09885ae21dd7726e8de9c66df6865/functions/__fzf_reverse_isearch.fish#L4) of `__fzf_reverse_isearch` uses `printf` to print a selection, it cannot handle such histories well.

I don't know why `printf` is needed to be used here for the purpose.  I think `commandline -rb (printf $select)` can be simplified to `commandline -rb (echo $select)` or `commandline -rb "$select"`, but I'm not sure.

Are there some reasons to use `printf`?

**Comment by jethrokuan** [comment]
Hi @yuttie,

thanks for the kind words!

> Are there some reasons to use printf?

No particular reason at all. These are remnants from code a long time ago. I'll be pushing a fix in a while.

**Comment by yuttie** [comment]
Great!
Now, it works well.
Thanks for your quick update!
