### ISSUE TITLE
Latest version returns no results

### ISSUE THREAD

**Issue by LkeMitchll** [fisherman/fzf#34]
The latest version at HEAD `1b96a2b` returns no results on CTRL-T the interface appears and the progress spinner also runs but I'm left with `0/0` every time. Running `fzf` works fine it seems to be this wrapper that's the issue.

If I revert to the `0.16.5` (`fisher fzf@0.16.5`) tag everything is fine again.

Let me know if I can provide some sort of debug output to help you out more.

Head:
![head](https://cloud.githubusercontent.com/assets/1729878/23547959/336ef74e-fffd-11e6-9a32-8629cc82eaf3.gif)

0.16.5:
![older](https://cloud.githubusercontent.com/assets/1729878/23547965/3865c8d6-fffd-11e6-82a9-f8ebc382a54a.gif)

**Comment by jethrokuan** [comment]
Sorry I missed this. Thanks for the detailed report!
Could you try this for me:

```
set -l FZF_FIND_FILE_COMMAND "command find -L \$PWD -mindepth 1 \\( -path \$PWD'*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' \\) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null | cut -b3-"

eval $FZF_FIND_FILE_COMMAND
```

**Comment by jethrokuan** [comment]
I think I fixed your issue, could you try again? thanks.

**Comment by LkeMitchll** [comment]
@jethrokuan That seems to have worked well, thanks very much!
