### ISSUE TITLE
control + r only works after I install fzf

### ISSUE THREAD

**Issue by domoritz** [fisherman/fzf#35]
Right after I install fzf, I can use reverse search. However, as soon as I open a new session, it does not work any more until I uninstall and reinstall the fzf plugin. How can I help you to debug this?

**Comment by jethrokuan** [comment]
How are you installing the fzf plugin? This could be an issue of fzf not
being in your path.

**Comment by domoritz** [comment]
I'm on OSX and use homebrew to install fzf. 

```
$ fzf --version                                                                                                                                                       0.16.6
$ which fzf
/usr/local/bin/fzf
```

**Comment by jethrokuan** [comment]
Are you using fish, and did you install this wrapper? If so, how did you do
it? I'm guessing you may be at the wrong repo

**Comment by domoritz** [comment]
Yes, I use `fish, version 2.5.0` and `fisherman version 2.12.0 ~/.config/fish/functions/fisher.fish`. I installed this wrapper with `fisher fzf`. 

What's funny is that reverse search in iTerm 2 version 3 works well when I uninstall this wrapper (`fisher uninstall fzf`) and then install it again.

**Comment by jethrokuan** [comment]
Are you receiving any errors when pressing Ctrl-R? This could be a fish + iTerm issue.

**Comment by domoritz** [comment]
No, no errors whatsoever. Simply nothing happens when I try to do a reverse search.

**Comment by jethrokuan** [comment]
Are you using vim keybindings? Could you try typing this into your terminal in the case where `Ctrl-r` doesn't work, and try `Ctrl-r` again?

```
bind \cr '__fzf_reverse_isearch'
```

**Comment by domoritz** [comment]
I don't think I am using vim keybinding. However, after I call `bind \cr '__fzf_reverse_isearch'` in the session, I can use reverse search again.

**Comment by jethrokuan** [comment]
Can you check if your config.fish does anything fishy, like bind C-r? That
is, are you using fisherman to manage all your fish config? Your
config.fish takes precedence over whatever fisherman manages.

**Comment by domoritz** [comment]
That was the right hint.

Somehow this command does not work anymore and it broke reverse search. Thank you @jethrokuan!

```fish
function fish_user_key_bindings
  bind \e\e 'thefuck-command-line'  # Bind EscEsc to thefuck
end
```

**Comment by domoritz** [comment]
For ref, I was using the suggestion from https://github.com/oh-my-fish/plugin-thefuck#optional-key-binding

**Comment by jethrokuan** [comment]
Fisherman modifies fish_user_key_bindings under the hood as well, so doing
that would override all keybindings that fisherman tries to install for
you. I believe the plugin you referenced has a fisherman-friendly version
as well (:

**Comment by domoritz** [comment]
I only found the omf wrapper. Do you remember where you saw the fisherman-friendly version?

**Comment by jethrokuan** [comment]
Oh I saw wrong. I guess there isn't one, but making one would be a simple
fork. I could do it, if you want.

**Comment by domoritz** [comment]
That would be sweet. I like to use the `esc+esc` keybinding when I messed up a command. But typing `fuck` is also not a big deal.

**Comment by jethrokuan** [comment]
Done! `fisher i jethrokuan/thefuck` should do it. 

the command seems pretty slow though.

**Comment by domoritz** [comment]
Awesome. It works well. You are right, it is slow but that's not a problem
with your wrapper.
