### ISSUE TITLE
Cannot use multiple FZF_DEFAULT_OPTS

### ISSUE THREAD

**Issue by p0deje** [fisherman/fzf#37]
When I set more than one option in FZF_DEFAULT_OPTS, it fails to properly recognize them when using keybindings:

```fish
set -U FZF_DEFAULT_OPTS "--reverse --exact"
```

```fish
 ~ __fzf_reverse_isearch
unknown option: --reverse --exact
```

Using fzf directly with `__fzfcmd` however works without any problems.

**Comment by jethrokuan** [comment]
just pushed a fix for this, do reopen if it doesn't work for you!

**Comment by p0deje** [comment]
Thank you so much, that was amazingly fast and it now works perfectly!
