### ISSUE TITLE
Use Ctrl-t binding for files

### ISSUE THREAD

**Issue by sooheon** [fisherman/fzf#39]
The new bindings replace `C-f`, which fish uses for completion of suggestions.

**Comment by jethrokuan** [comment]
Unfortunately `Ctrl-t` is also used to transpose characters. I'm reluctant to make changes again to the keybindings, which can surprise existing users

**Comment by sooheon** [comment]
Ah, forgot that one. Guess there are few binds which won't step on anyone's toes.
