### ISSUE TITLE
Use mlocate db on $HOME and up

### ISSUE THREAD

**Issue by Dietr1ch** [fisherman/fzf#47]
`find` is too slow for looking into `/` or `$HOME`

Using `locate` can't fully replace `find` as it may lead to cache inconsistencies, but it'll provide a nice speedup when you don't know where to `cd` to narrow your search space (and also when you are being lazy)

**Comment by jethrokuan** [comment]
@Dietr1ch sorry I took a while to reply. I actually don't use find myself - I customize the command to use rg via `FZF_FIND_FILE_COMMAND`:

`set -U FZF_FIND_FILE_COMMAND "rg --files"` is what I use, for example. Feel free to set that to `mlocate` if you see fit.

**Comment by EfforiaKnight** [comment]
@Dietr1ch I'm actually write it like this:
`function __fzf_locate --description "Search using locate command with fzf"`
`    set -q FZF_LOCATE_COMMAND`
`    or set -l FZF_LOCATE_COMMAND "command locate /"`
`    fish -c "$FZF_LOCATE_COMMAND" | eval "__fzfcmd -m $FZF_DEFAULT_OPTS $FZF_LOCATE_OPTS" | while read -l s; set selects $selects $s; end`
`    for select in $selects`
`        commandline -it -- "\"$select\""`
`        commandline -it -- " "`
`    end`
`    commandline -f repaint`
`end`

and `$FZF_LOCATE_OPTS` looks like this:
`--preview 'rougify {} 2>/dev/null' --header-lines=1 --preview-window hidden --bind '?:toggle-preview' --history='/home/efforia/.cache/FZF_history'`

Hope it helps.

**Comment by Dietr1ch** [comment]
I'm already using FZF_FIND_FILE_COMMAND to use mlocate and use relative
paths, but I meant to discuss whether having it use mlocate and find
depending on the current directory would be a better default.

Using find on home is slow, and using mlocate inside a code repo or other
quickly changing directory gets stale data.

I'm not completely sure which one to make a default, and which directories
need the other. Also I haven't thought about what should happen on remote
directories like nfs or sshfs mounts.

On Sep 1, 2017 04:27, "EfforiaKnight" <notifications@github.com> wrote:

@Dietr1ch <https://github.com/dietr1ch> I'm actually write it like this:
function __fzf_locate --description "Search using locate command with fzf"
set -q FZF_LOCATE_COMMAND
or set -l FZF_LOCATE_COMMAND "command locate /"
fish -c "$FZF_LOCATE_COMMAND" | eval "__fzfcmd -m $FZF_DEFAULT_OPTS
$FZF_LOCATE_OPTS" | while read -l s; set selects $selects $s; end
for select in $selects
commandline -it -- "\"$select\""
commandline -it -- " "
end
commandline -f repaint
end

and $FZF_LOCATE_OPTS looks like this:
--preview 'rougify {} 2>/dev/null' --header-lines=1 --preview-window hidden
--bind '?:toggle-preview' --history='/home/efforia/.cache/FZF_history'

Hope it helps.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fisherman/fzf/issues/47#issuecomment-326557292>, or mute
the thread

**Comment by EfforiaKnight** [comment]
I see. So like @jethrokuan said you can use rg. I personally use the_silver_searcher aka ag.

**Comment by jethrokuan** [comment]
I'm inclined to leave `find` as the default, because `find` is universal, while `locate` is not: not all distros come with `locate` by default, and when they do, perhaps in different flavours like `mlocate`.
