### ISSUE TITLE
ctrl-r cannot find  correctly

### ISSUE THREAD

**Issue by jinleileiking** [fisherman/fzf#48]
here is my history:

```

ansible-playbook maid.yml --list-tasks
ansible-playbook maid.yaml --list-tasks
ansible-playbook main.yaml --list-tasks
ansible-playbook main.yml --list-tasks
ansible-playbook maid.yml --help
sudo yum install ansible
mkdir ansible
```

when ctrl-r:
 
 
![default](https://user-images.githubusercontent.com/93968/30148809-b1b657c8-93d7-11e7-8c25-3af1e192571d.png)

**Comment by jethrokuan** [comment]
could you check if you have a history file in `~/.config/fish`? See https://github.com/fisherman/fzf/issues/29

**Comment by jinleileiking** [comment]
I use a script to import zsh history to fish. Maybe it has some bug

**Comment by jethrokuan** [comment]
sure, but have you checked if the history file exists there? also what version of fish are you on?

**Comment by jinleileiking** [comment]
fish, version 2.6.0-298-g5d2a806a

**Comment by jinleileiking** [comment]
```
> ~/o/_/logstash-output-kafka on master ◦ cat  ~/.config/fish/fish_history                                                                                                                                                         20:48:57
- cmd: l
   when: 1501740934
- cmd: cp ~/.zshrc ~/.fishrc
   when: 1501741046
- cmd: vim ~/.fishrc
   when: 1501741084
- cmd: . ~/.fishrc
   when: 1501741087
   paths:
    - .
- cmd: source ~/.fishrc
   when: 1501741110
- cmd: sour
   when: 1501741113
- cmd: source
   when: 1501741115
- cmd: .
   when: 1501741119
   paths:
    - .
- cmd: mv ~/.fishrc ~/.config/fish/config.fish
   when: 1501741290
- cmd: ls ~/.config/fish/config.fish
   when: 1501741305
- cmd: cat ~/.config/fish/config.fish
   when: 1501741316
- cmd: ll
   when: 1501741412
- cmd: omf update
   when: 1501741510
- cmd: curl -L https://get.oh-my.fish | fish
   when: 1501741529
- cmd: omf
   when: 1501741534
```

**Comment by jinleileiking** [comment]
functions/__fish_history.fish  I have not this file

**Comment by jethrokuan** [comment]
that `__fish_history.fish` file is deprecated, using the builtin `history` should suffice. Please remove the history file in `~/.config/fish/` see https://github.com/fish-shell/fish-shell/issues/862

**Comment by jpeeler** [comment]
I'm also having difficulty with the history. In my case, after I press ctrl-r I see:

```
 0/0 -S

>
```

And after attempting to search for something I get:

`history: Unknown option “--null”`

No idea what I'm doing wrong.

**Comment by jethrokuan** [comment]
Hi @jpeeler, it's likely you're on an old version of fish, could you check? `fish -v`. `history` has the `--null` switch with version `>2.4.0`

**Comment by jpeeler** [comment]
It didn't even occur to me to check the version of fish I'm using. Fedora's copy (2.3.1) is way more outdated than expected, so after upgrading using OBS all is well. Thanks!

**Comment by jinleileiking** [comment]
seems I found error location .

**Comment by bryaan** [comment]
Im having the same problem as @jpeeler.  Fish version 2.7.1
