### ISSUE TITLE
KeyBindings only work on terminal session where a fresh install happened.

### ISSUE THREAD

**Issue by cesarandreslopez** [fisherman/fzf#51]
On Ubuntu 17.04 after doing a fresh install:
fisher fzf

A ctrl R will invoke history search as intended.

After this, once i close the terminal search and do Ctrl R, history search will not show up and I will get 'fzf' on screen instead.

I can uninstall and install again and it will work once again, that is until the terminal session is terminated; any new terminal session on fish will show 'fzf' again.

Same issue happens on Ubuntu 16.04 LTS

Any suggestions?

fzf --version
0.17.3 (390b496)

**Comment by cesarandreslopez** [comment]
A bit more data.

Ctrl X works OK. The issue seems to appear on the rest of the bindings.

**Comment by jethrokuan** [comment]
This issue happened to me before with `urxvt`, and my conclusion was that this was the fault of the terminal emulator. Using `xterm` made it work alright. Not sure what went wrong though.

**Comment by tasmo** [comment]
Have the same problem.  
After a clean install in the running session it works, in a new session it doesn't. The only dirrerence is that neither `\cx` nor any other fzf shortcut seem to work.

Tried it in different terminal emulators, in the linux console and in and out of tmux.

`fisherman version 2.13.2 ~/.config/fish/functions/fisher.fish`
`fzf --version 0.17.1`

**Comment by mwilliammyers** [comment]
Yeah same thing happened to me, it looks like it is left over from running fzf's own installer [script](https://github.com/junegunn/fzf/blob/master/install) that handles key bindings...

**Comment by jethrokuan** [comment]
yep looks like a lot has changed upstream, I pushed a fix (I think). Let me know if there are still issues.

**Comment by ReneFroger** [comment]
Still having the same issue here.

**Comment by ReneFroger** [comment]
In `~/.config/fish/functions/fish_user_key_bindings.fish`, remove the call to fzf key bindings (line 2 I believe).

Then change   `if test "$FZF_LEGACY_KEYBINDINGS" -eq 1` to `    if test "$FZF_LEGACY_KEYBINDINGS" -eq 0` and it's working again.

**Comment by solars** [comment]
I'm having the same issue - @ReneFroger but I don't have this file at all, was there a change?

**Comment by ReneFroger** [comment]
I have solved it, but I don't remember exactly how. Perhaps install fzf with Fisher?

**Comment by solars** [comment]
@ReneFroger that's what I did - but the bindings only work in the terminal I used to install it, not if I open a new one..

**Comment by ReneFroger** [comment]
Try to install with FZF-way then with Fisher, and then reboot. You need to figure things out on yourself, like I did.

**Comment by jethrokuan** [comment]
@solars it's probably this;

**Comment by jethrokuan** [comment]
you may also need to check if the original `fzf`s keybindings are installed somehow by your package manager.

**Comment by jethrokuan** [comment]
You may check `with bind -P` I believe, I'm not on fish atm because fish 3.0 uses 100% of my CPU.

**Comment by solars** [comment]
hm weird, CTRL bindings I only have these:

bind -M insert \cy yank
bind -M insert \cx fish_clipboard_copy
bind -M insert \cv fish_clipboard_paste
bind -M insert \cl echo\ -n\ \(clear\ \|\ string\ replace\ \\e\\\[3J\ \"\"\)\;\ commandline\ -f\ repaint
bind -M insert \cc __fish_cancel_commandline
bind -M insert \cu backward-kill-line
bind -M insert \cw backward-kill-path-component
bind -M insert \cd delete-or-exit
bind \cy yank
bind \cx fish_clipboard_copy
bind \cv fish_clipboard_paste
bind \cl echo\ -n\ \(clear\ \|\ string\ replace\ \\e\\\[3J\ \"\"\)\;\ commandline\ -f\ repaint
bind -m insert \cc __fish_cancel_commandline
bind \cu backward-kill-line
bind \cw backward-kill-path-component
bind \cd delete-or-exit
bind -M visual \cy yank
bind -M visual \cx fish_clipboard_copy
bind -M visual \cv fish_clipboard_paste
bind -M visual \cl echo\ -n\ \(clear\ \|\ string\ replace\ \\e\\\[3J\ \"\"\)\;\ commandline\ -f\ repaint
bind -M visual -m default \cc end-selection force-repaint
bind -M visual \cu backward-kill-line
bind -M visual \cw backward-kill-path-component
bind -M visual \cd delete-or-exit
bind \cr history-search-forward

**Comment by jethrokuan** [comment]
all files in `conf.d` are sourced automatically with fish `>= 2.2`, https://github.com/jorgebucaran/fisher/issues/510

**Comment by solars** [comment]
hmm that's weird.. I have no idea why this doesn't work then, I started with fish 2.7.3

**Comment by solars** [comment]
I really don't understand, if I open the shell I can see (echo) that conf.d/fzf_key_bindings.fish
is executed. I can also see that the functions are available in the file as I can directly call them there.

**Comment by jethrokuan** [comment]
what else is being loaded? What does your `~/.config/fish` directory contain?

**Comment by solars** [comment]
These are the relevant files: https://gist.github.com/solars/c229ff1fe489ce59cd7fb6d88076fdab
I'm not sure if something could clash here, but as it seems the keybindings are either not set or somehow unset afterwards?

**Comment by jethrokuan** [comment]
https://gist.github.com/solars/c229ff1fe489ce59cd7fb6d88076fdab#file-config-fish-L22-L27

overrides your keybindings entirely. You'll want to move those stuff out of the function block, and delete the function altogether.

**Comment by solars** [comment]
Damn, thanks so much @jethrokuan I did not realize the function overrides them :/
