### ISSUE TITLE
FZF_FIND_FILE_COMMAND not respected

### ISSUE THREAD

**Issue by andyperisho** [fisherman/fzf#52]
I have this:

```
❯ echo $FZF_DEFAULT_COMMAND 
ag -l --hidden --ignore .git
```

But, when I run `fzf, the command is not respected. Files that are under `.gitignore` are printed.

On the other hand, when I run this:
```
env FZF_DEFAULT_COMMAND="ag -l --hidden --ignore .git" fzf
```
Then ag is correctly used.

Any idea what's going on?

**Comment by jethrokuan** [comment]
`$FZF_DEFAULT_COMMAND` is not a variable we use in this plugin. You might be looking for `$FZF_FIND_FILE_COMMAND` instead.

**Comment by andyperisho** [comment]
Yes I got both setup actually, but my `.gitignore` file is not being respected.

**Comment by jethrokuan** [comment]
It could then be that you're using the [official fzf plugin](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish), and not this one.

**Comment by andyperisho** [comment]
I removed it from pacman, and ran `__fzf_install`
Then, I set `$FZF_FIND_FILE_COMMAND`
And still, .gitignore is not being respected.

Besides, you say in the README that the recommend way of installing fzf is via the package manager. If so, then why does the official fzf plugin fail?

**Comment by jethrokuan** [comment]
> Besides, you say in the README that the recommend way of installing fzf is via the package manager. 

I recommend this because it's good to have your package manager manage the binary versions.

> If so, then why does the official fzf plugin fail?

as long as `fzf` is available in your `PATH`, then the package manager would've succeeded. Depending on the package configuration however, it may not add the keybindings for you.

That said, now that you have installed the binary via the helper function. Can I now check:

1. Where is `fzf` being sourced from? `which fzf`

**Comment by andyperisho** [comment]
I'm using pacman on arch, if that helps. `pacman -S fzf`

For now, I'm using the script installation, and here goes the outputs you asked for:
```
❯ which fzf
/home/merlin/.fzf/bin/fzf
```

I'm not using any keybings. I simply run `fzf` in a directory containing a `.gitignore`.

```
❯ functions __fzf_find_file
# Defined in /home/merlin/.config/fish/functions/__fzf_find_file.fish @ line 1
function __fzf_find_file
	set -q FZF_FIND_FILE_COMMAND
  or set -l FZF_FIND_FILE_COMMAND "command find -L \$PWD -mindepth 1 \\( -path \$PWD'*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' \\) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null"
  eval "$FZF_FIND_FILE_COMMAND" | eval "__fzfcmd -m $FZF_DEFAULT_OPTS $FZF_FIND_FILE_OPTS" | while read -l s; set selects $selects $s; end
  for select in $selects
    commandline -it -- "\"$select\""
    commandline -it -- " "
  end
  commandline -f repaint
end
```

**Comment by jethrokuan** [comment]
> /home/merlin/.fzf/bin/fzf

this is fine, it shows you're now using the fzf binary installed via this plugin.

> I'm not using any keybings. I simply run fzf in a directory containing a .gitignore.

here lies your problem. `fzf` is generally meant to be piped to, and not called directly on its own. You'll want to be calling `__fzf_find_file`, or:

```
ag -l --hidden --ignore .git | fzf
```

**Comment by andyperisho** [comment]
Hmmm but that defeats the purpose of having a global variable set in the first place.
Besides, running `__fzf_find_file` also does not respect ag, but I guess that's because it is using a custom `FZF_FIND_FILE_COMMAND`.

So, if I use `__fzf_find_file` on it's own, I can't actually create custom filtering.
If I use `fzf` on it's own, I need to pipe `ag` to it, or instead set an `FZF_FIND_FILE` as an env before it.

If i'm correct, then this makes the global `FZF_FIND_FILE` pointless because it is used in neither case! Correct?

**Comment by jethrokuan** [comment]
where did you get the idea that `FZF_FIND_FILE` was used anywhere? I don't think i've mentioned that anywhere.

what do you mean by you can't create custom filtering? doesn't `set -U FZF_FIND_FILE_COMMAND "ag -l --hidden --ignore .git" do the job?

**Comment by jkryanchou** [comment]
Cool. I have set the `FZF_FIND_FILE_COMMAND` env and it could work well. Thanks for the issue.
