### ISSUE TITLE
No FZF env vars respected.

### ISSUE THREAD

**Issue by bryaan** [fisherman/fzf#53]
So as soon as I install this all these options die:

FZF_DEFAULT_COMMAND
FZF_DEFAULT_OPTS

FZF_CTRL_T_COMMAND
FZF_CTRL_T_OPTS

FZF_ALT_C_COMMAND
FZF_ALT_C_OPTS

and I'm sure many more.  

Given this package is *supposed* to be just some keybindings it shouldn't be touching these.

**Comment by jethrokuan** [comment]
If you really wanted to keep those options and keybindings, you should install the fish file provided in the official fzf repo.

The keybindings in this plugin are different, and naming the options `CTRL_T` when it isn't ctrl-t makes no sense to me.
