### ISSUE TITLE
reverse search not working for two different reasons (on two almost identical ubuntu 16.04 installations)

### ISSUE THREAD

**Issue by arooni** [fisherman/fzf#60]
ENV 1: Ubuntu 16.04 LTS server
fish version: 2.7.1
issue: hitting reverse search and picking an option, i'm then presented with : 

[I]  brazil ÓÇ∞ ~/.c/f/functions ÓÇ∞ ÓÇ† master ¬± ÓÇ∞ Could not send process 29782, '__fzfcmd' in job 2, 'history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r ' from group 29137 to group 29457
setpgid: Operation not permitted
Could not send job 2 ('history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r ') to foreground
tcsetpgrp: No such process
fish
<W> fish: Could not send job 2 (‚Äúhistory | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r | read -l select‚Äù) to foreground
tcsetpgrp: No such process

ENV 2: Ubuntu 16.04 Laptop:
fish version: 2.7.1
doing reverse search on this enviornet *does* allow me to select something, but in between prints these messages:

[I]  ~  --color: command not found
- (line 2):
            --color info:33,prompt:33,pointer:166,marker:166,spinner:33 -q (commandline)
            ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on line 2 of file ~/.config/fish/functions/__fzf_reverse_isearch.fish

in function “__fzf_reverse_isearch”
        called on standard input

**Comment by jethrokuan** [comment]
For env 1, the issue might be related to this: https://github.com/fish-shell/fish-shell/issues/4715

You could try running the minimal testcase `echo | sed &` and see if there's an error there.

for env 2, could you print the contents of your options? `$FZF_DEFAULT_OPTS` and `$FZF_REVERSE_ISEARCH_OPTS`.

**Comment by arooni** [comment]
For ENV1: I ran that:
got a usage message
[I]  brazil ÓÇ∞ ~ ÓÇ∞ echo | sed &
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --follow-symlinks
                 follow symlinks when processing in place
  -i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
  -l N, --line-length=N
                 specify the desired line-wrap length for the `l' command
  --posix
                 disable all GNU extensions.
  -r, --regexp-extended
                 use extended regular expressions in the script.
  -s, --separate
                 consider files as separate rather than as a single continuous
                 long stream.
  -u, --unbuffered
                 load minimal amounts of data from the input files and flush
                 the output buffers more often
  -z, --null-data
                 separate lines by NUL characters
      --help     display this help and exit
      --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.

**Comment by arooni** [comment]
For env2: 
[I]  ~  echo $FZF_DEFAULT_OPTS
--color fg:240,bg:-1,hl:33,fg+:241,bg+:223,hl+:33
            --color info:33,prompt:33,pointer:166,marker:166,spinner:33
[I]  ~ 

apparently that second var wasn't set
[I]  ~  echo $FZF_REVERSE_ISEARCH_OPTS

[I]  ~ 


Thanks for your help!

**Comment by jethrokuan** [comment]
Output of your test command in env1 looks correct. I'm not sure what's going on there, but it seems your shell doesn't have permissions to some command (`setpgid`), and is unrelated to this plugin.

**Comment by arooni** [comment]
@jethrokuan problem #1, it looks like upgrading to a nightly build of fish resolved[ the setpgid issue ](https://github.com/fish-shell/fish-shell/issues/4776#issuecomment-370202634).

However I still have this color issue on both Mac OS X and Ubuntu 16.04... same error and same fzf default and reverse options.

**Comment by arooni** [comment]
Kind of unrelated; but...

with set -U FZF_LEGACY_KEYBINDINGS 0

on both mac & ubuntu
```
alt + x ==> yields

[N]  ~/.c/fish  fish: Unknown command '__fzf_find_and_execute'

```

Every other command works well (with the exception of control r which complains about the color). that being said, happy it's working and i can ignore that message for now.

ps; thanks for the great features... couldn't imagine not having them

**Comment by jethrokuan** [comment]
I removed the remnants of `find_and_execute` in #61 , didn't find it particularly useful. I don't do much work here, some of the features I really like are implemented by others as well :smile:

**Comment by jethrokuan** [comment]
can i check what `fzf` version you're on?

**Comment by arooni** [comment]
No worries; I think having a chance to edit your command is more useful as well..

On Mac: [I]  ~  fzf --version
0.17.3 (brew)

On ubuntu:
[I]  /tmp  fzf --version
0.17.1 (0b33dc6)

**Comment by jethrokuan** [comment]
That looks recent enough for `--color` to exist. I'm quite certain the color issue is an error in your variable configuration on your end, since the code base does not set any `color` options by default.

**Comment by arooni** [comment]
Well thanks for taking the time to look at my issue.. I grep'd for and
color settings that might be in my fish config and didn't see anything that
stuck out.

Regardless, I can just ignore the complaint since the code works.


may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>
