### ISSUE TITLE
Unknown command '__fzf_cd_with_hidden'

### ISSUE THREAD

**Issue by codemonkey800** [fisherman/fzf#62]
I'm using the legacy keybindings. When I use Alt+Shift+C, I get the error `fish: Unknown command '__fzf_cd_with_hidden'`.

I'm guessing it's because the following lines haven't been updated:
https://github.com/fisherman/fzf/blob/5999526b2ab387c90e52625b9049175f2f87f47c/key_bindings.fish#L5
https://github.com/fisherman/fzf/blob/5999526b2ab387c90e52625b9049175f2f87f47c/key_bindings.fish#L11

I'm guessing changing it to `__fzf_cd --hidden` will fix the issue.

**Comment by jethrokuan** [comment]
Thanks for pointing it out, fix is now in master.
