### ISSUE TITLE
Geeting some weird issue

### ISSUE THREAD

**Issue by ikouchiha47** [fisherman/fzf#72]
fish: Unknown command 'fzf'                                                                                                                    0 < 13:57:05
- (line 1):
begin; fzf --read0 --tiebreak=index --toggle-sort=ctrl-r --height 40% -q (commandline)
       ^
from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.7.1/share/fish/functions/eval.fish

in function 'eval'
	called on line 2 of file ~/.config/fish/functions/__fzf_reverse_isearch.fish

in function '__fzf_reverse_isearch'
	called on standard input

**Comment by jethrokuan** [comment]
you will need to install the `fzf` binary, which does not come with this plugin. See https://github.com/junegunn/fzf#installation

**Comment by ikouchiha47** [comment]
oh ok, sorry
