### ISSUE TITLE
Add command to history when using `__fzf_open` (Ctrl-o)

### ISSUE THREAD

**Issue by carlosdagos** [fisherman/fzf#74]
Hello, thanks for this plugin! 

I think it would be convenient to have the command executed by `__fzf_open` added to the history.

Right now, if I open a file using `Ctrl-o`, do something to the file and close the editor, but want to open it again, I have to hit `Ctrl-o` again and search for the file again, instead of just pressing the up arrow which would be just a tiny bit more convenient. 

Not a huge deal because if I type `$EDITOR` and then do `<Ctrl-g> + <file fuzzy search>`, that is stored to history but it's not as convenient as `Ctrl-o` 😄 

Thanks!

**Comment by jethrokuan** [comment]
Thanks @carlosdagos , mergedd!
