### ISSUE TITLE
Get latest release from Github API

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fzf#8]
Right now the version for `fzf` is hard-coded. It would be great to be able to query github's API to figure out the latest fzf release. This should be done without any external dependencies, like JSON parsers.

**Comment by bucaran** [comment]
What are the end points?

**Comment by jethrokuan** [comment]
`GET /repos/:owner/:repo/releases/latest`

**Comment by jethrokuan** [comment]
hmm odd, my `curl`s don't show anything

**Comment by thuandt** [comment]
I submit my PR to solve this issue.

**Comment by jethrokuan** [comment]
Fixed and merged.
